captures-dir: src/main/resources/captures/
admin:
password:
smtp:
  address:
  password:
spring:
  data:
    mongodb:
      auto-index-creation: true
  resources:
    static-locations:
logging:
  file:
    name: src/main/resources/application.log
  level:
    root: WARN

